apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx-deployment
  labels:
    app: custom-nginx
spec:
  replicas: 2  # Number of desired pods
  selector:
    matchLabels:
      app: custom-nginx
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
      - name: custom-nginx
        image: custom-nginx:latest  # Use the Docker image built earlier
        ports:
        - containerPort: 80  # NGINX listens on port 80
---
apiVersion: v1
kind: Service
metadata:
  name: custom-nginx-service
spec:
  selector:
    app: custom-nginx
  ports:
  - protocol: TCP
    port: 80  # Service port
    targetPort: 80  # Container port
  type: LoadBalancer

